# Generated by Django 4.2.8 on 2024-07-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('metaLucro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
            preserve_default=False,
        ),
    ]
