# Generated by Django 4.2.8 on 2024-07-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidadeMedida', models.CharField(max_length=20)),
                ('codDeBarra', models.CharField(max_length=50)),
                ('valorVenda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
