# Generated by Django 4.2.8 on 2024-08-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='natureza',
            field=models.CharField(blank=True, choices=[('imposto', 'imposto'), ('produto', 'produto'), ('funcionario', 'funcionario')], max_length=20, null=True),
        ),
    ]
